import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })
type Data = {
  name: string;
  size: number;
  error?: any;
}

export default function Home() {
  const handleClick = async () => {
    const headers = {
      'Accept': 'application/json',
      'Content-Type': 'application/json'
    }
    const data: Data = await fetch('/api/html', { headers, body: JSON.stringify({
      "target_url": "https://manhua.idmzj.com/tags/search.shtml?s=%E8%BF%99%E4%B8%AA%E5%B0%B1%E6%98%AF%E5%83%B5%E5%B0%B8%E5%90%97",
      "wait_eval": "document.querySelector('div.tcaricature_block2').children.length > 2",
      "pick_selectors": ["div.tcaricature_block2"]
    })}).then(res => res.json());
    console.log(data);
  }
  return (
    <>
      <Head>
        <title>Test Demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <button onClick={handleClick}>click</button>
      </main>
    </>
  )
}
